### ISSUE TITLE
2020-03-23 23:41:29 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.

### ISSUE THREAD

**Issue by SirGoodenough** [kalkih/mini-media-player#256] opened 2020-03-24 05:05 UTC
Started noticing a warning in my log.  Not sure if it's your media player or not, but I thought I would let you know in case it's a thing.   I have HA media players and yours loaded from hacs, based on the message, I'm guessing they changed something i you in 107.5.

```
2020-03-23 23:41:29 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.

2020-03-23 23:41:56 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.

2020-03-24 00:00:40 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.
```

**Comment by kalkih** [comment] 2020-03-24 05:44
Duplicate of #244, #251, #252

**Closed** 2020-03-24 05:44 UTC
Labels: duplicate
