### ISSUE TITLE
sync_volume does not work if Swap volume slider for buttons is enabled

### ISSUE THREAD

**Issue by igudjonsson75** [kalkih/mini-media-player#573] opened 2021-11-18 21:42 UTC
I have a Sonos group and if I enable Swap volume slider for buttons the sync_volume feature does not work. If i have it disabled the sync_volume does work

**Comment by kalkih** [comment] 2021-11-22 18:15
Duplicate of https://github.com/kalkih/mini-media-player/issues/151

**Closed by kalkih** 2021-11-22 18:15 UTC
Labels: duplicate
