### ISSUE TITLE
HA 2023-11 dissapear message text box for tts

### ISSUE THREAD

**Issue by EdwardR21** [kalkih/mini-media-player#788] opened 2023-11-11 22:09 UTC
I've update home assistant to Core 2023.11.2 and Front-End 20231030.2, on previus versions t was work great, but in this version the message text box for tts was not enabled, only  the send button, and when this button is press i see message "required key not provide data['message']", in test from home assistant services, tts works normaly with my Echo devices. One more thing, i've the last version from mini media player (1.16.5) and alexa media player on latest version (4.7.9)

![2023-11-11 17_02_11-Estancias – Home Assistant](https://github.com/kalkih/mini-media-player/assets/105020053/3c983276-5e7a-43a1-b573-b0c84c78dcd1)

**Comment by th3dll** [comment] 2023-11-12 03:07
I'm having this issue as well. I cannot seem to get tts working anymore.

**Comment by flyman1664** [comment] 2023-11-12 15:53
You can check this post as a temporarily workaround

https://github.com/kalkih/mini-media-player/issues/785

**Comment by EdwardR21** [comment] 2023-11-12 22:54
@flyman1664 thanks, its work for me !

**Comment by kalkih** [comment] 2023-11-15 14:24
Duplicate of #785

**Closed by kalkih** 2023-11-15 14:24 UTC
Labels: duplicate
