### ISSUE TITLE
Two issues with progress bar

### ISSUE THREAD

**Issue by 03397** [kalkih/mini-media-player#269] opened 2020-04-04 16:26 UTC
I have found two issues with the progress bar.

During playing the progress bar works just fine but if I switch to another card at the top and back to the mini media player card the progress is  frozen but the playback is continuing. 

In addition, when I stop the playback the progress bar is keep counting seconds.

**Comment by kalkih** [comment] 2020-04-04 16:58
What media player integration are you seeing this with?

**Comment by 03397** [comment] 2020-04-04 17:07
With Sonos.

**Comment by 03397** [comment] 2020-04-04 20:25
Another issue is If refresh the url at the media player card the drop down list arrow dissappears.
![after_refresh](https://user-images.githubusercontent.com/6150853/78460669-64cfcc80-76cb-11ea-9597-1a5bad596299.GIF)
![before_refresh](https://user-images.githubusercontent.com/6150853/78460670-65686300-76cb-11ea-9336-11cf92c9b36b.GIF)

You can at the pictures also the counter regarding my previous post.

**Comment by 03397** [comment] 2020-04-05 12:26
I am not want to give you more information. I think the issue with the dissapearing icons is created because of vertical stack I am using.

**Comment by kalkih** [comment] 2020-04-05 17:54
Was not able to reproduce the progress tracking continuing after pausing playback, does it always happen?
The freezing after changing tab was easy to reproduce and I will fix that.

**Comment by 03397** [comment] 2020-04-05 18:00
Yes it happens always. Just pause and notice the number of the progress bar. Then if you switch card and come back you will see that the progress bar has moved and the number is not the same.
So if you pause for two hours the progress bar will be moved two hours ahead.

I am using vertical stack and the progress bar is at the second card if this matters.

**Comment by 03397** [comment] 2020-04-05 18:03
Have you managed to reproduce the disappearing icons issue?
This should be easy to reproduce too.

**Comment by kalkih** [comment] 2020-04-05 18:36
> Yes it happens always. Just pause and notice the number of the progress bar.

No this doesn't happen to me, the progress stops correctly until I unpause again I don't own any Sonos, so not sure if the issue is specific to Sonos.



> Have you managed to reproduce the disappearing icons issue?
> This should be easy to reproduce too.

No, never seen that happen.

**Comment by 03397** [comment] 2020-04-05 19:10
Have you tried to reproduce it using vertical stack?

Because it does not happen otherwise.
Use my setup. Maybe you can reproduce both issues.

**Comment by kalkih** [comment] 2020-04-05 19:47
Ok, please post your config (inside a code block).

**Comment by 03397** [comment] 2020-04-05 20:10
`cards:
  - artwork: full-cover-fit
    entity: media_player.sonos_one
    hide:
      controls: true
      icon: true
      info: true
      name: true
      power: true
      progress: true
      source: true
      volume: true
    type: 'custom:mini-media-player'
  - entity: media_player.sonos_one
    hide:
      info: false
      power: true
      runtime: false
      shuffle: false
    info: scroll
    name: Master Bedroom
    type: 'custom:mini-media-player'
type: vertical-stack
`

**Comment by 03397** [comment] 2020-04-05 20:16
> > `cards:
  - artwork: full-cover-fit
    entity: media_player.sonos_one
    hide:
      controls: true
      icon: true
      info: true
      name: true
      power: true
      progress: true
      source: true
      volume: true
    type: 'custom:mini-media-player'
  - entity: media_player.sonos_one
    hide:
      info: false
      power: true
      runtime: false
      shuffle: false
    info: scroll
    name: Master Bedroom
    type: 'custom:mini-media-player'
type: vertical-stack

**Comment by kalkih** [comment] 2020-04-07 18:15
Hello, I've now tried with you config and can't see any of the two issues (disappearing icons or progress continuing after pausing).

The issue regarding progress tracking not working when leaving the tab and coming back has been addressed and will be included in the next release #272

**Comment by kalkih** [comment] 2020-04-07 18:16
![Kapture 2020-04-07 at 20 12 20 2](https://user-images.githubusercontent.com/457678/78704709-8d92d480-790c-11ea-8c97-ac76901a01e2.gif)

Do you happen to use any specific theme or plugins in chrome that could cause this?

**Comment by 03397** [comment] 2020-04-07 18:30
The disappearing icons issue have been solved after installing mini media player from HACS.
The issue with the progress bar it still there.
You need to pause, switch to a different card from Home Assistant and then come back.
You will see that the progress bar moved forward since the pause.
I am using Sonos. Do you think this might cause the issue?

**Comment by kalkih** [comment] 2020-04-07 18:43
Okay, great!

If it's just when you're switching between tabs it should be fixed with https://github.com/kalkih/mini-media-player/pull/272 as well 👍

**Comment by PD75** [comment] 2020-04-08 09:48
I also have problem with the progress and runtime:
![image](https://user-images.githubusercontent.com/10294795/78770069-6b419b00-798e-11ea-94d5-21a949a62533.png)
Without runtime:
![image](https://user-images.githubusercontent.com/10294795/78770341-bc518f00-798e-11ea-8abd-2f3a095b18be.png)
Normal Media Player:
![image](https://user-images.githubusercontent.com/10294795/78770167-83191f00-798e-11ea-855e-a131702d04a6.png)

I am using mpd.

```
entity: media_player.music_player_daemon
group: true
hide:
  power_state: false
  shuffle: false
  volume: true
  progress: false
  runtime: false
icon: 'mdi:music-circle'
info: short
source: icon
type: 'custom:mini-media-player'
```

**Comment by mwasowski** [comment] 2020-04-16 13:45
I can say I experience something related?

At the beginning it's fine for few seconds, but then this starts to happen more and more:
![qUZjWyyXjp](https://user-images.githubusercontent.com/1921808/79463524-3fab5a00-7ff9-11ea-9a6a-749391452aff.gif)
This happened when I sipped ahead in Spotify desktop app:
![1jQGHH2bKc](https://user-images.githubusercontent.com/1921808/79463541-45a13b00-7ff9-11ea-8482-4f7290e62a3d.gif)
And here you see that current time is kinda longer than the song itself ;)
![firefox_GigDkkX8AT](https://user-images.githubusercontent.com/1921808/79463578-4cc84900-7ff9-11ea-94d7-b4f82a266468.png)
My config:
```
entity: media_player.spotify
type: 'custom:mini-media-player'
artwork: cover
source: icon
hide:
  volume: true
  runtime: false
style: |
  ha-card {
    height: 100px;
  }
  ha-card .mmp-player {
    margin: auto 0;
  }
```

**Comment by 03397** [comment] 2020-05-17 20:53
I have upgraded to version 1.8.0.
Problem with the status bar still there .
After pause counter and bar keeps counting.

**Comment by mwasowski** [comment] 2020-05-17 21:51
Same here. The bar skips like in my previous gifs and counts past song length.

**Comment by kalkih** [comment] 2020-05-18 07:22
@03397 
> You need to pause, switch to a different card from Home Assistant and then come back.
> You will see that the progress bar moved forward since the pause.
> I am using Sonos. Do you think this might cause the issue?

Is this the issue you're having or does it also happen when just pausing and not switching tabs?

@mwasowski Does the skipping and ticking past the track length occur on the default media control card as well?

**Comment by 03397** [comment] 2020-05-18 07:50
@kalkih 
It seems now you do not need to changes tabs. It changes every time the card refreshes.

**Comment by mwasowski** [comment] 2020-05-18 09:06
@kalkih Ok, I just added standard media control card for testing and it behaves in a similar way. Maybe it's not skipping back and forth like before, but does skip forward. And definitely not counting the time right. I am suspecting that it's the Spotify integration :( When I pause from the card it pauses playback, but when I pause from Spotify the progress bar and time continues to move :( Also, when I pause the playback with the progress bar and time ahead, it snaps back to correct position:
![OLrdcpq0WP](https://user-images.githubusercontent.com/1921808/82194704-82fa3080-98f7-11ea-9cd3-f0069ad8b920.gif)

**Comment by kalkih** [comment] 2020-05-18 13:04
@mwasowski 
Thanks for the details.
Okay, yes I believe I've seen this behaviour as well, I believe it started after the rework of the Spotify component. If the underlying data isn't accurate there's not much I can do about that particular issue unfortunately.

@03397 Ok, what media player component are you using where you see this behaviour?

**Comment by 03397** [comment] 2020-05-18 13:12
I am using a Sonos Media Player.

**Comment by mwasowski** [comment] 2020-05-18 14:05
@kalkih I was afraid it's not related to the mini-media-player since after your suggestion it bugs out on the default card the same way. I guess it has to be moved upstream if you won't be able to find anything.

**Comment by kalkih** [comment] 2020-05-18 14:16
Yes you are right, the only thing I could do would be to limit it from going past the length of the media, but that won't help the out of sync issue.

**Comment by mwasowski** [comment] 2020-05-18 15:11
@kalkih It might seem like a dumb question but is this the right place to report this?
https://github.com/home-assistant/core

**Comment by kalkih** [comment] 2020-05-18 15:14
@mwasowski yes, that's the correct place 👍🏼

**Comment by kalkih** [comment] 2021-09-30 14:06
Still having this issue?

**Comment by 03397** [comment] 2021-09-30 14:39
@kalkih 
Both issues has been solved by your last commit

**Closed** 2021-09-30 15:24 UTC
Labels: bug
