### ISSUE TITLE
0.115 Browse media Feature

### ISSUE THREAD

**Issue by thib5** [kalkih/mini-media-player#417] opened 2020-09-18 18:25 UTC
Hi ! I really like your card ( more customization ) but the new feature of Media Browsing in media control card for 0.115 is really cool !! do you think you could integrate it ? 

Thanks 

( Bonus may be integrate spot cast ? )

**Comment by kalkih** [comment] 2020-09-18 20:48
Hello, thank you!
Duplicate of #413

**Closed by kalkih** 2020-09-18 20:48 UTC
Labels: duplicate
