### ISSUE TITLE
Warning media_player_thumbnail is deprecated

### ISSUE THREAD

**Issue by Aiace88** [kalkih/mini-media-player#251] opened 2020-03-19 15:00 UTC
Hi, i have update to 0.107.1 and now i have this message in the logs.

2020-03-19 15:24:34 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.

**Comment by kalkih** [comment] 2020-03-19 19:05
Hello,
Duplicate of #244

**Closed by kalkih** 2020-03-19 19:05 UTC
Labels: duplicate
