### ISSUE TITLE
Icons missing in HA 0.110.beta

### ISSUE THREAD

**Issue by mgiako** [kalkih/mini-media-player#302] opened 2020-05-18 11:07 UTC
Since I installed the latest HA beta (0.110.0b3) my mediaplayers don't show the icons anymore.
The commands in more-info window works, but in lovelace the icons are missing.
Not only the "automatic icons" (Power, play,next stop ecc.), but also the ones in the custom shortcuts.
It's only me?

**Comment by kalkih** [comment] 2020-05-18 12:58
Hello, this was fixed in the latest release https://github.com/kalkih/mini-media-player/pull/301

**Comment by mgiako** [comment] 2020-05-18 13:22
@kalkih sorry,I had a problem and not really on 1.8.0, but...

even now, the normal icons are back, but the shortcut icons not:

![image](https://user-images.githubusercontent.com/44270368/82217268-7c30e500-991a-11ea-99fc-dc5d49772538.png)

this is my config:
```
         - type: custom:mini-media-player
            entity: media_player.tvsala
            volume_stateless: true
            source: full
            hide:
              power: true            
            shortcuts:
               columns: 5 # Max buttons per row
               buttons:
                 - icon: mdi:power
                   type: service
                   id: script.turn_on
                   data:
                     entity_id: script.toggletv
                 - name: INFO
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: info
                 - name: TV
                   type: source
                   id: DTV
                 - name: PC
                   type: source
                   id: HDMI 1
                 - name: Playst
                   type: source
                   id: HDMI 2

                 - icon: mdi:play
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: play
                 - icon: mdi:pause
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: pause
                 - icon: mdi:stop
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: stop
                 - icon: mdi:fast-forward
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: ffwd
                 - icon: mdi:record-rec
                   type: service
                   id: remote.send_command
                   data:
                      entity_id: remote.broadlink
                      device: television
                      command: record
```

**Comment by kalkih** [comment] 2020-05-18 13:23
Okay I'll look into the shortcut icons.

**Comment by RogerSelwyn** [comment] 2020-05-18 16:07
I can confirm I don't get shortcut icons. I'm using latest HA dev (pulled today), and MMP 1.8.0.

**Comment by kbalint** [comment] 2020-05-19 19:26
Home Assistant 0.110.0.dev20200512 + 1.8.0 fresh install
![image](https://user-images.githubusercontent.com/4146263/82369443-54737700-9a17-11ea-9252-681954b1ec45.png)
majority of the icons missing, can't controll really anything.

**Comment by kalkih** [comment] 2020-05-19 19:30
@kbalint Try clearing cache if you've updated the card, most icons will show up again with the latest version of the card (see screenshot posted above). Rest of the icons will be fixed with #304 (shortcut icons / dropdown icon)

**Comment by kbalint** [comment] 2020-05-19 20:44
@kalkih cache was the first I tried, but to no avail.

**Comment by kalkih** [comment] 2020-05-19 20:47
Check your resource reference, reinstall from HACS if installed from there.

**Comment by kbalint** [comment] 2020-05-19 21:00
@kalkih it was installed manually for a year or so, and have this problem since the last update to the HA *-latest docker image next week or so. I've updated mmp from HACS _today_ right before submitting - but has the same glitched ui; cache cleared and no errors in the console.

**Comment by kalkih** [comment] 2020-05-19 21:11
@mgiako @RogerSelwyn New release available, should fix the last missing icons, please give it a shot and let me know, thanks!

**Comment by kalkih** [comment] 2020-05-19 21:15
@kbalint Hmm... not really sure then, try hitting the "reload resources" button from the HA UI (in the three dot menu in the header).

**Comment by RogerSelwyn** [comment] 2020-05-19 21:16
> @mgiako @RogerSelwyn New release available, should fix the last missing icons, please give it a shot and let me know, thanks!

That seems to have fixed it.

**Comment by mgiako** [comment] 2020-05-19 21:34
@kalkih problem solved, thanks!
@kbalint maybe you have mine same initial problem, tell me: what do you have in resources: ?
this 
```
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
```
or this
``` 
      - url: /hacsfiles/mini-media-player/mini-media-player.js
      type: module
```

**Comment by kalkih** [comment] 2020-05-20 07:46
Great, thanks for the help 👍

**Closed by kalkih** 2020-05-20 07:46 UTC
Labels: bug
