### ISSUE TITLE
0.107.b0+ warning

### ISSUE THREAD

**Issue by roblandry** [kalkih/mini-media-player#244] opened 2020-03-14 22:05 UTC
2020-03-14 17:55:18 WARNING (MainThread) [homeassistant.components.media_player] The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.

**Comment by cobch** [comment] 2020-03-26 20:49
@roblandry  Any news about that? I got the same problem.

**Comment by kalkih** [comment] 2020-03-26 20:51
It's fixed, will be included in the next release, just ignore the warning until then, it's just deprecated not removed.

**Comment by cobch** [comment] 2020-03-26 21:02
@kalkih Thanks for the quick answer. It was annoying since I do not get anymore the artwork on the Apple TV integration. I will be patient till then (-:

**Comment by kalkih** [comment] 2020-03-26 21:04
That shouldn't be related to this issue, does the Apple TV integration expose artwork?

**Comment by postlund** [comment] 2020-03-26 21:22
It does and it should work assuming artwork is available (i.e. not streaming via AirPlay as was just concluded on the community forums) and you are using the beta component.

**Comment by cobch** [comment] 2020-03-27 06:53
@postlund So it is confirmed that the Artwork is not working when you stream via Airplay? Strange because before it was working perfectly. Any link I can read more about that?

**Comment by postlund** [comment] 2020-03-27 07:05
@cobch I streamed something from Spotify on my phone via AirPlay yesterday and looked the the MRP logs (`atvremote --debug ... playing`) and no artwork or other metadata were present. So at least it did not work for me then. If it did indeed work before, then something has changed. Which apps are you streaming with btw?

**Comment by cobch** [comment] 2020-03-27 12:40
Sorry but what is btw? Before the Apple TV integration was recognising the songs and showing the artwork but something happen and nothing is appearing now anymore )-:

**Comment by postlund** [comment] 2020-03-27 12:51
@cobch You need to be more specific if I should be able to answer or analyze this (when was "before", does it work I regular apps, software versions, etc).

**Comment by cobch** [comment] 2020-03-27 12:58
I will try to look more specific when the problem started but is is not easy to remember on which version of Hassio and ATv it was working. I only updated these before it started to stop. I will try to have a look on my backup if I manage to dig something better...

**Comment by postlund** [comment] 2020-03-27 13:13
We are getting a bit out-of-topic here, but I just want to clarify that you are running the beta component from https://github.com/postlund/hass-atv-beta with an Apple TV 4(K) at least? Can you try if metadata works with some app on the device, e.g. Netflix or something? I have only seen AirPlay provide metadata i some specific cases, like streaming something from iTunes/the TV app on my mac. It has never worked with Spotify for instance.

**Comment by cobch** [comment] 2020-03-27 13:25
Yes of course. Running pyatv 0.5.0 update 3 with my AppleTV4K.
I proposed you to continue this thread where it started (for me)

https://community.home-assistant.io/t/apple-tv-component-does-not-work-on-tvos-13/120682/75

**Closed** 2020-03-31 15:55 UTC
Labels: enhancement

**Comment by jurgenweber** [comment] 2020-10-09 01:15
I am still getting this in 0.116.1 and 

```
    - url: /local/custom_ui/mini-media-player-bundle.js?v=1.11.0
      type: module
```

Thanks

**Comment by jurgenweber** [comment] 2020-10-09 01:21
ahhhhhh, user issue.. my bad.

Thanks
