### ISSUE TITLE
entity__icon should use the entity state for its color

### ISSUE THREAD

**Issue by michaelarnauts** [kalkih/mini-media-player#186] opened 2019-11-10 10:57 UTC
The `entity__icon`  always has the blueish color, even when the entity is active. This looks inconsistent with other elements.

Both devices are on:
![image](https://user-images.githubusercontent.com/1193779/68542891-e89dbb00-03b0-11ea-9d03-988102f7cd61.png)

Both devices are off:
![image](https://user-images.githubusercontent.com/1193779/68542902-fe12e500-03b0-11ea-8a71-1da2634a0f98.png)

**Comment by kalkih** [comment] 2019-11-10 13:32
Duplicate of #144

**Closed by kalkih** 2019-11-10 13:32 UTC

**Comment by kalkih** [comment] 2020-01-08 21:47
This is now available in the latest release.
> Entity icon color based on state is now supported, although disabled by default.
> 
> See the new `icon_state` option in the [hide option object](https://github.com/kalkih/mini-media-player#hide-object)
> 
> Enable icon state color:
> 
> ```yaml
> - type: custom:mini-media-player
>   ...
>   hide:
>     icon_state: false
> ```
> 
> Thanks!
