### ISSUE TITLE
Mini-media-Player "Media Browser" instead of "Source"

### ISSUE THREAD

**Issue by Coucougamin** [kalkih/mini-media-player#627] opened 2022-03-06 12:40 UTC
Hi,

I believe that mini-medi-player is very helpfull and would be even better if instead of the "source" dropdown list it would be possible to change it by the "media browser" button that appeared on the default HA media player, allowing to select any media.

To explain myself, see the pictures attached :
Pic 1 : my dashboard showing one default HA media player from HA  + 3 mini media player (Poolhouse is unplugged ...)
Pic 2 : shows the dropdown list from the mini media player
Pic 3 : shows the media browser from the default HA media player

Is this possible in any way to get access to this "media browser" from the mini media player or is this something that could be worked out soon ?

In any case, thanks for the very good work that really helps me setting up my perfect HA dashboard !

Have a great day !
![pic1 - 1 default HA media player + 3x mini media-player](https://user-images.githubusercontent.com/101047553/156925248-a8cdbff1-5a4b-4cf5-b096-fa11fc380325.png)
![pic2 - source dropdwon list from mini media player](https://user-images.githubusercontent.com/101047553/156925252-e4bb1a70-2cc3-45ab-9c78-d3ad3c131bdf.png)
![pic3 - Media browser from default HA media Player](https://user-images.githubusercontent.com/101047553/156925254-ad69122b-cf3d-4a80-a6c7-0e2b9783fe22.png)

**Comment by Stooovie** [comment] 2022-03-11 08:44
This has been requested for a very long time but AFAIK it hadn't been possible. Maybe the APIs have changed since.

**Comment by DaveCBr** [comment] 2022-03-11 12:20
Yes but the standard media player card now works by default in that way, so it must be possible.

**Comment by kalkih** [comment] 2022-03-11 18:43
Duplicate of #435

@Stooovie is correct, this hasn't been possible, and still isn't possible as far as I know.

@DaveCBr 
Custom cards doesn't have the same prerequisites as the cards that's part of the core codebase unfortunately.

**Closed by kalkih** 2022-03-11 18:43 UTC
