### ISSUE TITLE
Input select drop down appears behind other elements

### ISSUE THREAD

**Issue by tomlut** [kalkih/mini-media-player#204] opened 2019-12-17 09:40 UTC
The most recent updates, v1.5.1 and v1.5.0 have caused the drop down list to appear behind other elements:

![Screenshot_2019-12-17 Home Assistant](https://user-images.githubusercontent.com/10679300/70983604-1d6a0400-210d-11ea-8daa-2a2b7668f33b.png)

v1.4.2 does not display this way.

![Screenshot_2019-12-17 Home Assistant(2)](https://user-images.githubusercontent.com/10679300/70984464-a03f8e80-210e-11ea-991e-36545155a03e.png)

**Comment by ASNNetworks** [comment] 2019-12-17 15:12
Yes, I have experienced this suddenly as well. I tried downgrading, but it didn't solve it. I thought perhaps my theme was broken so I changed some stuff. Then I experienced this with all themes (including default).

**Comment by kalkih** [comment] 2019-12-17 16:12
Hello, duplicate of #201, #203.

The issue was introduced in v1.5.0 and fixed in v1.5.1 (42be01b37ed891b8b34d33b62c8172777bff22aa).

If you still have the issue, make sure you're really on version v1.5.1, try clearing cache or reinstalling the card if using HACS.

Thanks!

**Closed by kalkih** 2019-12-17 16:12 UTC
Labels: bug, duplicate
