### ISSUE TITLE
Icons not cumming up sincs 0.110

### ISSUE THREAD

**Issue by antoinevandenhurk** [kalkih/mini-media-player#309] opened 2020-05-23 05:13 UTC
Since update 0.110 I have problems loading the icons of this custom mini media player. Under Windows 10 with Chrome I managed after cleared cached memory, but not via my tablet and phone. 
I have applied Google's solution ([https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DAndroid&hl=en](url)), it seems to be fine after this, but when the site is reloaded, the icons do not come along again ...

`entities:
  - entity: media_player.kodi_w
    group: true
    state_color: true
    type: 'custom:mini-media-player'
  - entity: media_player.kodi_c
    group: true
    state_color: true
    type: 'custom:mini-media-player'
  - entity: media_player.medion_tv
    group: true
    hide:
      controls: true
    icon: 'mdi:television-classic'
    show_source: true
    state_color: true
    type: 'custom:mini-media-player'
    volume_stateless: true
  - entity: media_player.stb_arris_uhd
    group: true
    hide:
      controls: false
      power_state: false
      volume: true
    icon: 'mdi:satellite-uplink'
    state_color: true
    type: 'custom:mini-media-player'
    volume_stateless: true
  - entity: media_player.jbl_link104986
    group: true
    hide:
      controls: true
    icon: 'mdi:cast-audio'
    show_source: true
    state_color: true
    type: 'custom:mini-media-player'
  - entity: media_player.chromecast0241
    group: true
    hide:
      controls: false
    icon: 'mdi:google-chrome'
    show_source: true
    state_color: true
    type: 'custom:mini-media-player'
  - entity: media_player.pioneer_av_center
    group: true
    hide:
      controls: false
      power_state: false
    icon: 'mdi:amplifier'
    state_color: false
    type: 'custom:mini-media-player'
  - input_select.kodikeuze
  - input_select.muziekkeuze
show_header_toggle: false
title: Mediacenter
type: entities
`

![Screenshot_20200522-074315](https://user-images.githubusercontent.com/35188384/82722184-a0971380-9cc4-11ea-8111-899981578a7a.png)

**Comment by sandman32** [comment] 2020-05-23 09:17
In the 3 dot menu of home assistant try reloading resources.  It fixed the problem for me, also this is a dupe of a issue.   https://github.com/kalkih/mini-media-player/issues/302

**Comment by caro7372** [comment] 2020-05-23 15:49
Hi,

I have the same problem on my iPhone that the icons are not visible anymore.
Running on 0.110.1 and updated to v1.8.1

Regards,

Robert
![IMAGE 2020-05-23 17:49:12](https://user-images.githubusercontent.com/63898040/82734824-b8e74c80-9d1d-11ea-835c-c8a27eb22573.jpg)

**Comment by kalkih** [comment] 2020-05-23 21:36
This was fixed in the latest release, see https://github.com/kalkih/mini-media-player/issues/302

So if you've updated it's most likely a cache issue, try what @sandman32 suggested, and double check your resource reference and make sure it's good.

**Closed by kalkih** 2020-05-23 21:36 UTC
Labels: duplicate

**Comment by caro7372** [comment] 2020-05-23 21:58
Hi, good evening,

I still have a question about the icons.
On the laptop everything is oke but on the iPhone it isn’t.
Is that still the problem with the cache? Why should it be oke then on the laptop?

Where and how to clear the cache then?

Sorry for the questions, still a lot to learn ;-)

Kind Regards and stay safe,

Robert

**Comment by kalkih** [comment] 2020-05-23 22:12
Hello,

Caching in this case is done locally on your device.
So the browser on your laptop has most likely dropped the old version from cache and loaded the updated one. Your iPhone is probably still hanging on to the old version, try the three dot menu int he HA header -> reload resources or look in safari/chrome (whatever you use) settings and see if you can clear the cache from there.

Hope this helps 🤞

**Comment by caro7372** [comment] 2020-05-23 22:31
Hi,

I finally found it but in iPhone I had to go to the app configuration!
Reset Front-end Cache did the trick.

Regards,

Robert

**Comment by kalkih** [comment] 2020-05-23 22:39
Perfect! I'm sure that's helpful for someone else as well, thanks for sharing!

Take care.
