### ISSUE TITLE
1.16.6 volume slider invisible in Dark Mode

### ISSUE THREAD

**Issue by dy-nz** [kalkih/mini-media-player#800] opened 2023-12-04 19:56 UTC
Hi. Version 1.16.6's volume line/slider is invisible in Dark Mode. Everything else is visible.
This was tested in iOS Google Chrome, with latest versions of HAOS and HA Core installed. 
Thanks, David

**Comment by Drafteed** [comment] 2023-12-04 23:22
I can't reproduce this. Can you show a screenshot and give more detailed information about the device and iOS version? You can also try clearing your cache in Chrome app.

**Comment by dy-nz** [comment] 2023-12-05 02:23
Hi. I am using the latest HA companion app on an Apple iPhone 11, iOS version 17.1.2 - the latest as at 4 December 2023. I cleared the iOS Safari cache and ran it in Incognito mode to access my Pi 4 HA site (running on the latest versions of Core and OS). I I've attached the screen shots. I also ran the iOS Chrome browser incognito, but without clearing the cache but shouldn't have made any difference. Chrome was version 120.0.6099.50 . All 4 screen shots are attached - Light/Auto mode (since it was midday) and Dark mode. Thanks for the work to date, and for following up on this so quickly.

![Safari Light-Auto](https://github.com/kalkih/mini-media-player/assets/58097849/30cb87ba-452f-4984-b80d-97f2df0aa1e2)
![Safari Dark](https://github.com/kalkih/mini-media-player/assets/58097849/9b0a654e-3b7e-4329-a85d-4d591af7daa7)
![Chrome Light-Auto](https://github.com/kalkih/mini-media-player/assets/58097849/ce719ec4-521e-4384-b9c6-27f7ee03cb66)
![Chrome Dark](https://github.com/kalkih/mini-media-player/assets/58097849/df42e011-4723-4c4a-a45a-d4d2633c3cc0)

**Comment by dy-nz** [comment] 2023-12-05 03:14
I should add my HA config.
Lovelace...
    card:
      type: custom:mini-media-player
      entity: media_player.zm_speakers
      name: Speakers
      volume_step: '3'
      hide:
        power: true
        icon: true
        source: true
        play_pause: true
        volume_level: false

State variable....
update.mini_media_player_update:
state: off
auto_update: false
installed_version: v1.16.6
in_progress: false
latest_version: v1.16.6
release_summary: null
release_url: https://github.com/kalkih/mini-media-player/releases/v1.16.6
skipped_version: null
title: null
friendly_name: Mini Media Player update

**Comment by dy-nz** [comment] 2023-12-05 07:03
Hi. Re testing.
I'm not a developer so don't have an HA dev environment, but i know a bit about testing.
Happy to test alphas and beta releases if I can be of use.
Cheers, David

**Comment by NasaGeek** [comment] 2023-12-21 06:02
This this is fixed with https://github.com/home-assistant/frontend/pull/19102

**Closed** 2024-01-26 09:46 UTC
