### ISSUE TITLE
Cover doesn't show up

### ISSUE THREAD

**Issue by darox** [kalkih/mini-media-player#67] opened 2019-01-24 10:37 UTC
I'm using this code:
`- type: custom:mini-media-player`
   `   entity: media_player.buro`
   `   artwork: cover`
   `   power_color: true`
   `   hide_volume: false`
   `   show_progress: true`

However, the background is not showing up as background. Player is Sonos and source Spotify. 
https://imgur.com/a/83G6ukp

Resources are imported via
`resources:`
   ` - url: /local/mini-media-player-bundle.js?v=0.9.8`
     ` type: module`

YAML spacing somehow doesn't work...

**Comment by kalkih** [comment] 2019-01-24 13:17
Hey, can you please check the browser developer console for potentional error messages?

**Comment by darox** [comment] 2019-01-24 13:22
Only error:
Manifest: property 'theme_color' ignored, 'hsl(var(--huesat) 80%)' is not a valid color.
app-0fd67575.js:89 [Violation] 'setTimeout' handler took 56ms

**Comment by kalkih** [comment] 2019-01-24 13:36
Okay, and the Home Assistant log (`/dev-info`)?
Are you running HA behind SSL?

**Comment by darox** [comment] 2019-01-24 14:00
No log entry in /dev-info

Yes, nginx and cloud flare.

**Comment by kalkih** [comment] 2019-01-24 21:36
Hmm, does it work if you access HA through witout ssl?

**Comment by darox** [comment] 2019-01-25 12:44
No, even with both Proxies it's not visible.

**Comment by darox** [comment] 2019-01-26 13:14
It was my fault, I could fix it. I forgot, that I disabled the artwork in the configuration.yml a few months ago. No it works. Sorry!

**Comment by kalkih** [comment] 2019-01-26 13:39
Okay, absolutely no worries, you found the cause which is what matters.

Yes, those are based on the `accent-color` theme variable, will look to add a seperate theme variable for them in the next release.

Closing this.

**Closed by kalkih** 2019-01-26 13:39 UTC
Labels: bug
