### ISSUE TITLE
tick boxes missing

### ISSUE THREAD

**Issue by Fred0172** [kalkih/mini-media-player#427] opened 2020-10-19 14:34 UTC
Hello,

I have the speaker group working, on my laptop I see the tick boxes to group speakers
But on my tablet I see only the name. without tick boxes, I can click on the name but that's no very easy as it is to small
I rather have tick box so I know what is selected

here my card config
type: 'custom:mini-media-player'
entity: media_player.livingroom
hide:
  power: false
  icon: false
  source: false
speaker_group:
  platform: sonos
  show_group_count: true
  entities:
    - entity_id: media_player.livingroom
      name: Sonos Woonkamer
    - entity_id: media_player.keuken
      name: Sonos keuken
    - entity_id: media_player.tuinkamer
      name: Sonos Tuinkamer
    - entity_id: media_player.badkamer
      name: Sonos Badkamer
    - entity_id: media_player.prieel
      name: Sonos Prieel
    - entity_id: media_player.sonos_kiara
      name: Sonos Kiara

Thanks for all the support

**Comment by jodur** [comment] 2020-10-25 08:49
I have the same problem swith the latestest 116.x versions

**Comment by ALaDoffe** [comment] 2020-10-26 06:31
Hi 
Same for me
Ok on FireFox but KO with Safari or Ios MobileApp

**Comment by kalkih** [comment] 2020-12-26 13:48
Duplicate of #418

**Closed by kalkih** 2020-12-26 13:48 UTC
Labels: duplicate
