### ISSUE TITLE
Controls disappeared after updating to HA 2021.11.0

### ISSUE THREAD

**Issue by erd82** [kalkih/mini-media-player#559] opened 2021-11-03 22:15 UTC
After updating to HA 2021.11.0 the controls for all mini-media-player cards disappeared.
![mini-media-player-controls](https://user-images.githubusercontent.com/63564291/140200817-c2d32359-b75f-489d-a3bd-e24ea22551eb.gif)

Clearing the browser cache did not help. Any idea what to do?

**Comment by deluxestyle** [comment] 2021-11-03 22:33
Same issue here

**Comment by nickrout** [comment] 2021-11-03 22:34
They seem to still be there, just invisible. Does this post give a clue? 

https://community.home-assistant.io/t/2021-11-icon-picker-device-links-and-entity-categories/352836/65?u=nickrout

**Comment by ZizzyZA** [comment] 2021-11-04 04:39
Just came here to ask the same question, controls definitely still there, but invisible. Hover still shows control background colour change & pointer cursor.

**Comment by grozanski** [comment] 2021-11-04 08:17
The same issue here

**Comment by grozanski** [comment] 2021-11-04 08:18
The same issue here

**Comment by deluxestyle** [comment] 2021-11-04 08:21
the new beta version fixed the issue

**Comment by VictoriousCupid** [comment] 2021-11-04 14:04
this seems to be related to [](https://github.com/home-assistant/frontend/issues/10521)

**Comment by sven41** [comment] 2021-11-04 15:29
Same problem
![afbeelding](https://user-images.githubusercontent.com/60574634/140355314-45e98954-050d-410a-ba27-5157594894a6.png)

**Comment by ovitters** [comment] 2021-11-04 16:52
As it took me a while to figure out how to install the beta version in HACS:

- Go to _HACS_
- Go to _Frontend_
- Go to _Mini Media Player_
- Click the three dots, _Reinstall_
- Enable _Show beta versions_, then select `v1.14.0-beta`
- Click the Install button

**Comment by kalkih** [comment] 2021-11-04 20:56
Will do a stable release later tonight

**Comment by kalkih** [comment] 2021-11-04 21:09
Duplicate of https://github.com/kalkih/mini-media-player/issues/555

New stable release is now out so should be no need to switch to the beta anymore.

Thanks!

**Closed by kalkih** 2021-11-04 21:09 UTC
Labels: duplicate

**Comment by erd82** [comment] 2021-11-04 21:26
Cool, it's working also for me again in HA 2021.11. Thanks for the quick support !!

**Comment by nickrout** [comment] 2021-11-04 22:41
Thanks for fixing it so quickly @kalkih

**Comment by h3nrytan** [comment] 2021-11-05 04:20
![icon](https://user-images.githubusercontent.com/3590384/140457506-806456af-a96f-4aaf-ad81-64cb5a73b6bf.png)
thanks for the fix! 

minor detail: i notice the icon may require padding at the bottom to make it center.

**Comment by verstrepeng** [comment] 2021-11-05 09:36
I'm in 1.14, but still missing the icons...

Config:
`          - type: "custom:mini-media-player"
            entity: media_player.keuken
            icon: mdi:music-box-outline
            toggle_power: false
            info: scroll
            more_info: false
            max_volume: 40
            volume_stateless: true
            #replace_mute: play_pause
            hide:
              power_state: false
              progress: true
              controls: false
              icon: true
              mute: true
              volume_level: false
            shortcuts:
              hide_when_off: false
              columns: 4
              buttons:
                - id: 'http://opml.radiotime.com/Tune.ashx?id=s6503&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085'
                  name: StuBru
                  type: music
`
![image](https://user-images.githubusercontent.com/16412175/140489867-e78e6dc7-e466-4d68-b9f7-a571b403dd2e.png)

**Comment by fedebruni84** [comment] 2021-11-05 10:22
> I'm in 1.14, but still missing the icons...
> 
> Config: - type: "custom:mini-media-player" entity: media_player.keuken icon: mdi:music-box-outline toggle_power: false info: scroll more_info: false max_volume: 40 volume_stateless: true #replace_mute: play_pause hide: power_state: false progress: true controls: false icon: true mute: true volume_level: false shortcuts: hide_when_off: false columns: 4 buttons: - id: 'http://opml.radiotime.com/Tune.ashx?id=s6503&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085' name: StuBru type: music
> 
> Screenshot: ![image](https://user-images.githubusercontent.com/16412175/140489867-e78e6dc7-e466-4d68-b9f7-a571b403dd2e.png)

I think you need to clear the browser cache

**Comment by verstrepeng** [comment] 2021-11-05 11:31
> > I'm in 1.14, but still missing the icons...
> > Config: - type: "custom:mini-media-player" entity: media_player.keuken icon: mdi:music-box-outline toggle_power: false info: scroll more_info: false max_volume: 40 volume_stateless: true #replace_mute: play_pause hide: power_state: false progress: true controls: false icon: true mute: true volume_level: false shortcuts: hide_when_off: false columns: 4 buttons: - id: 'http://opml.radiotime.com/Tune.ashx?id=s6503&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=f6cc6a101d38ff75b13940a8d20b7085' name: StuBru type: music
> > Screenshot: ![image](https://user-images.githubusercontent.com/16412175/140489867-e78e6dc7-e466-4d68-b9f7-a571b403dd2e.png)
> 
> I think you need to clear the browser cache

That did the trick... 
Thanks !

**Comment by srodighiero** [comment] 2021-11-06 19:45
I still have the problem, tried to clear cache, reinstall, reboot, nothing solved the issue

**Comment by olehdutko** [comment] 2021-12-16 17:23
Hello, icons is still invisible for mini-media-player-bundle.js v=1.15.0

**Comment by nickrout** [comment] 2021-12-16 19:35
Have you cleared your browser cache?

**Comment by olehdutko** [comment] 2021-12-16 20:42
Sorry, my fault! did not notice that I had another (very old)  version installed. Everything is working well.
