### ISSUE TITLE
Since 1.0.2 artwork cover do not show current status of the player

### ISSUE THREAD

**Issue by Obicom** [kalkih/mini-media-player#90] opened 2019-02-24 22:10 UTC
I have the issue that with version 1.0.2 the artwork cover (use full-cover) on multiroom group "überall" do not clear the cover when player stopped and show the artcover very late after starting the player. Any idea what I could do or test? In the screenshot the multiroom player stopped since hours:

![image](https://user-images.githubusercontent.com/25134482/53306110-44f39580-3889-11e9-9def-371300166526.png)

**Comment by kalkih** [comment] 2019-02-25 01:45
Does it go away if you refresh the page?
Also, what type of device is that?

**Comment by Obicom** [comment] 2019-02-25 06:09
With refresh no change. It is a Alexa multiroom group (a group with all my echos together to hear the same sound in all rooms simultaneous)

**Comment by kalkih** [comment] 2019-02-25 13:28
Then I would say there's something wonky going on with the alexa component, you are using the custom alexa as a media player right? But could very well be the intended behaviour, seems similar to how the spotify component behaves, it will show the last played media even though you haven't played anything in a while.

This card simply displays the data (attributes) reported by the backend.

You could try enabling the idle view feature of this card, this will hide some information such as the artwork when the entity state equals `standby`. This will of course only work if the echo component sets the entity state to standby after the entity has been idle for some time, but I think it does (#73).
```yaml
# mini-media-player card
...
idle_view:
  when_standby: true
  # There're more options such as when_paused etc, check the docs.
```

**Comment by Obicom** [comment] 2019-02-25 14:19
Player was on status paused (why?) but with when_paused: true cover is gone. 👍

**Comment by kalkih** [comment] 2019-02-25 14:25
I guess since it's basically a simulated device, it doesn't have to go idle, and is always ready to go.

Anyway, great that the idle view came in handy 👍🏼

Can I close this issue?

**Comment by Obicom** [comment] 2019-02-25 14:26
Yes, of course .. thank you very much for your kind support.

**Closed** 2019-02-25 14:28 UTC
Labels: bug
