### ISSUE TITLE
media_player.volumio 

### ISSUE THREAD

**Issue by Rapace29** [kalkih/mini-media-player#483] opened 2021-02-13 20:33 UTC
Thank's for your work.
I use it to on Home Assistant to remotely manage a volumio on an second raspberry.
The standard media-player card offer an option to browse the media options ( browse podcast for example ).
Could-you please consider to add this to your mini-media-player card ?

**Comment by RomRider** [comment] 2021-02-19 10:29
This is not possible yet because of https://github.com/home-assistant/frontend/issues/7145

**Comment by kalkih** [comment] 2021-03-21 13:47
Duplicate of https://github.com/kalkih/mini-media-player/issues/435

**Closed by kalkih** 2021-03-21 13:47 UTC
Labels: duplicate
