### ISSUE TITLE
Add option to display Media Browser like HA's built-in media player

### ISSUE THREAD

**Issue by nagyrobi** [kalkih/mini-media-player#419] opened 2020-09-19 20:52 UTC
With 0.115, a new great feature is added to the media players, Media Browser. On the builtin media player itself a new folder icon appears which clicked, displays a popup with the media files present on the device.

In mini-media-player, this should be as a programmable shortcut item (button) which could do two things at once: switch to the source (like 'USB' input) and also display a popup with the tracks, like HA's main media player.

**Comment by kalkih** [comment] 2020-09-19 22:03
Duplicate of https://github.com/kalkih/mini-media-player/issues/413

**Closed by kalkih** 2020-09-19 22:03 UTC
Labels: duplicate
