### ISSUE TITLE
volume_stateless: true results in sync function not working

### ISSUE THREAD

**Issue by madtraxx18** [kalkih/mini-media-player#596] opened 2022-01-29 15:31 UTC
So I really like the volume_stateless controls (without the slider)
But whenever this function is configured in a player the sync_volume function is not working.

If I changed the outline part below with volume_stateless: false the sync works again

  - type: custom:mini-media-player
    entity: media_player.woonkamer_sonos
    **_volume_stateless: true_**
    hide:
      power: true
    speaker_group:
      platform: sonos
      sync_volume: true
      show_group_count: true
      entities:
        - entity_id: media_player.keuken
          name: Sonos Keuken
    entities:
      - type: custom:mini-media-player
        entity: media_player.multiroom_player
        group: true
        source: icon
        artwork: cover
        info: short
        hide:
          volume: true
          power: true
      - type: custom:mini-media-player
        entity: media_player.keuken
        group: true
        hide:
          controls: true

**Comment by kalkih** [comment] 2022-02-11 16:59
Duplicate of #151

**Closed by kalkih** 2022-02-11 16:59 UTC
Labels: bug, duplicate
