### ISSUE TITLE
Dropdown chevrons not aligned anymore

### ISSUE THREAD

**Issue by thijselblaso** [kalkih/mini-media-player#326] opened 2020-06-03 08:51 UTC
After the update, the dropdown chevrons are not aligned when I open and close the dropdown.
Any idea why this happens? Is this a bug or is there something wrong in my configuration?

![close](https://user-images.githubusercontent.com/38098396/83616166-cc00e480-a587-11ea-849e-1144195fbce8.png)
![open](https://user-images.githubusercontent.com/38098396/83616184-d02d0200-a587-11ea-93b9-f5cdb95d4a4b.png)

**Comment by kalkih** [comment] 2020-06-07 17:13
Thanks, will fix.

Duplicate of #325

**Closed by kalkih** 2020-06-07 17:13 UTC
Labels: duplicate
